import React from "react";
import Head from "next/head";
import HeaderLayout from "../layouts/HeaderLayout";
import CoursesScreen from "../components/screens/CoursesScreen";
import { requireAuth } from "../utils/requireAuth";
import prisma from "../lib/prismadb";

type Props = {
  courses: Array<{
    id: string;
    name: string;
    term: number;
    description: string;
    open: boolean;
  }>;
};

const CoursesPage = ({ courses }: Props) => {
  return (
    <div>
      {" "}
      <Head>
        <title>E-class</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderLayout>
        <CoursesScreen courses={courses} />
      </HeaderLayout>
    </div>
  );
};

export async function getServerSideProps(context: any) {
  const data = await prisma.course.findMany();
  const courses = data;
  return { props: { courses } };
}

export default CoursesPage;
