import Head from "next/head";
import { unstable_getServerSession } from "next-auth/next";
import HeaderLayout from "../layouts/HeaderLayout";
import GradesScreen from "../components/screens/GradesScreen";
import { requireAuth } from "../utils/requireAuth";
import prisma from "../lib/prismadb";
import { authOptions } from "./api/auth/[...nextauth]";
import type { Grades } from "types";

export default function Home({ grades }: { grades: Grades }) {
  return (
    <div>
      <Head>
        <title>Hanozi-Class</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HeaderLayout>
        <GradesScreen grades={grades} />
      </HeaderLayout>
    </div>
  );
}

export async function getServerSideProps(context: any) {
  return requireAuth(context, async () => {
    const session = await unstable_getServerSession(context.req, context.res, authOptions);
    const email = session!.user!.email!;
    const data = await prisma.student.findMany({
      where: { email: email },
      select: { courses: { select: { course: true, grade: { select: { grade: true } } } } },
    });
    const grades = data[0].courses;
    let coursesToFind: Array<number> = [];
    return { props: { grades } };
  });
}
