import Head from "next/head";
import LoginScreen from "../components/screens/SignInScreen";
import HomeScreen from "../components/screens/HomeScreen";
import { useSession, getSession } from "next-auth/react";
import HeaderLayout from "../layouts/HeaderLayout";
import GradesScreen from "../components/screens/GradesScreen";
import { requireAuth } from "../utils/requireAuth";

export default function Home({ props }: any) {
  return (
    <div>
      <Head>
        <title>E-class</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderLayout>
        <GradesScreen />
      </HeaderLayout>
    </div>
  );
}

export async function getServerSideProps(context: any) {
  return requireAuth(context, () => {
    return { props: {} };
  });
}
