import Head from "next/head";
import LoginScreen from "../components/screens/LoginScreen";
import HomeScreen from "../components/screens/HomeScreen";
import { useSession } from "next-auth/react";
import HeaderLayout from "../layouts/HeaderLayout";

export default function Home() {
  const session = useSession();
  return (
    <div>
      <Head>
        <title>E-class</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderLayout>
        {session.status == "authenticated" && <HomeScreen />}
        {session.status == "unauthenticated" && <LoginScreen />}
      </HeaderLayout>
    </div>
  );
}

export async function getServerSideProps(props: any) {
  return { props: {} };
}
