import Head from "next/head";
import LoginScreen from "../components/screens/LoginScreen";
import HomeScreen from "../components/screens/HomeScreen";
import { useSession, getSession } from "next-auth/react";
import HeaderLayout from "../layouts/HeaderLayout";
import { ReactElement } from "react";
import { redirect } from "next/dist/server/api-utils";

export default function Home({ providers }: any): ReactElement {
  const session = useSession();
  return (
    <div>
      <Head>
        <title>E-class</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderLayout>
        {session.status == "authenticated" && <HomeScreen />}
        {session.status == "unauthenticated" && (
          <LoginScreen providers={providers} />
        )}
      </HeaderLayout>
    </div>
  );
}

export async function getServerSideProps(context: any) {
  const session = await getSession();
  if (!session) {
    return {
      redirect: {
        destination: "/signin/",
        permanent: false,
      },
    };
  }
}
