import React from "react";
import Head from "next/head";
import HeaderLayout from "../../layouts/HeaderLayout";
import CoursesScreen from "../../components/screens/CoursesScreen";
import { requireAuth } from "../../utils/requireAuth";
import prisma from "../../lib/prismadb";
import { unstable_getServerSession } from "next-auth";
import { authOptions } from "pages/api/auth/[...nextauth]";
import { PrismaClient, Session } from "@prisma/client";
import { useSession } from "next-auth/react";
import CoursesUserScreen from "components/screens/CoursesUserScreen";

type Props = {
  courses: Array<{
    id: number;
    name: string;
    term: number;
    description: string;
    open: boolean;
  }>;
};

const CoursesPage = ({ courses }: Props) => {
  const session = useSession();
  courses.sort((a, b) => (a.term > b.term ? 1 : -1));
  return (
    <div>
      {" "}
      <Head>
        <title>E-class</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <HeaderLayout>
        {session == undefined && <CoursesScreen courses={courses} />} {session && <CoursesUserScreen courses={courses} />}
      </HeaderLayout>
    </div>
  );
};

export async function getServerSideProps(context: any) {
  const session = await unstable_getServerSession(context.req, context.res, authOptions);
  let courses;
  if (!session) {
    // return all courses
    const data = await prisma.course.findMany();
    courses = data;
  } else {
    // return student's courses
    const email = session.user!.email!;
    const data = await prisma.student.findMany({
      include: {
        courses: true,
      },
      where: {
        email: email,
      },
    });
    const courseIds = data[0].courses.map((c: any) => c.courseId);
    courses = await prisma.course.findMany({
      where: { id: { in: courseIds } },
    });
    console.log(courses);
  }
  return { props: { session, courses } };
}

export default CoursesPage;
