name: Unit Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci --force
      - name: jest
        run: npm test
      - name: Cypress run
        uses: cypress-io/github-action@v4.1.0 # use the explicit version number
        with:
          build: npm run build
          start: npm start
